name: Build and push a branch gpu image to ghcr

on:
  workflow_dispatch:

jobs:
  branch-gpu-build-and-push:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
          with:
            ref: ${{ github.ref_name }}
        - uses: ./.github/actions/branch-build-and-push
          with:
            ghcr-password: ${{ secrets.GITHUB_TOKEN }}
            push-to-ghcr: true
            build-gpu: true
